// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.1
// source: telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BikeId        string                 `protobuf:"bytes,1,opt,name=bike_id,json=bikeId,proto3" json:"bike_id,omitempty"`
	BatteryLevel  float32                `protobuf:"fixed32,2,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	IsCharging    bool                   `protobuf:"varint,3,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Lat           float64                `protobuf:"fixed64,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          float64                `protobuf:"fixed64,6,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargingStatusRequest) Reset() {
	*x = ChargingStatusRequest{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargingStatusRequest) ProtoMessage() {}

func (x *ChargingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargingStatusRequest.ProtoReflect.Descriptor instead.
func (*ChargingStatusRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *ChargingStatusRequest) GetBikeId() string {
	if x != nil {
		return x.BikeId
	}
	return ""
}

func (x *ChargingStatusRequest) GetBatteryLevel() float32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *ChargingStatusRequest) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *ChargingStatusRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChargingStatusRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ChargingStatusRequest) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

type ChargingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargingStatusResponse) Reset() {
	*x = ChargingStatusResponse{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargingStatusResponse) ProtoMessage() {}

func (x *ChargingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargingStatusResponse.ProtoReflect.Descriptor instead.
func (*ChargingStatusResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ChargingStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\"\xba\x01\n" +
	"\x15ChargingStatusRequest\x12\x17\n" +
	"\abike_id\x18\x01 \x01(\tR\x06bikeId\x12#\n" +
	"\rbattery_level\x18\x02 \x01(\x02R\fbatteryLevel\x12\x1f\n" +
	"\vis_charging\x18\x03 \x01(\bR\n" +
	"isCharging\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x10\n" +
	"\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x12\n" +
	"\x04long\x18\x06 \x01(\x01R\x04long\"0\n" +
	"\x16ChargingStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2k\n" +
	"\x10TelemetryService\x12W\n" +
	"\x0eChargingStatus\x12 .telemetry.ChargingStatusRequest\x1a!.telemetry.ChargingStatusResponse(\x01B6Z4~/Users/peterwinzell/telemetry/api/proto;telemetrypbb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_proto_goTypes = []any{
	(*ChargingStatusRequest)(nil),  // 0: telemetry.ChargingStatusRequest
	(*ChargingStatusResponse)(nil), // 1: telemetry.ChargingStatusResponse
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.TelemetryService.ChargingStatus:input_type -> telemetry.ChargingStatusRequest
	1, // 1: telemetry.TelemetryService.ChargingStatus:output_type -> telemetry.ChargingStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
